---
apiVersion: v1
kind: Namespace
metadata:
  name: rhacs-operator
  labels:
    openshift.io/cluster-monitoring: "true"
  annotations:
    openshift.io/description: "Red Hat Advanced Cluster Security Operator"
    openshift.io/display-name: "RHACS Operator"
---
apiVersion: v1
kind: Namespace
metadata:
  name: stackrox
  labels:
    openshift.io/cluster-monitoring: "true"
  annotations:
    openshift.io/description: "Red Hat Advanced Cluster Security Services"
    openshift.io/display-name: "RHACS Services"

