---
apiVersion: v1
kind: Namespace
metadata:
  name: rhacs-operator
  labels:
    openshift.io/cluster-monitoring: "true"
  annotations:
    openshift.io/description: "Red Hat Advanced Cluster Security for Kubernetes"
    openshift.io/display-name: "RHACS"

