apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: permission-binder-operator-metrics
  namespace: monitoring
  labels:
    app.kubernetes.io/name: permission-binder-operator
    app.kubernetes.io/component: metrics
    release: prometheus
spec:
  selector:
    matchLabels:
      control-plane: controller-manager
  endpoints:
  - port: http
    path: /metrics
    interval: 30s
    scrapeTimeout: 10s
  namespaceSelector:
    matchNames:
    - permissions-binder-operator

