apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: permission-binder-operator-production

resources:
  - ../../crd/permission.permission-binder.io_permissionbinders.yaml
  - ../../deployment/operator-deployment.yaml
  - ../../configmap/permission-config.yaml
  - ../../permissionbinder/permissionbinder-example.yaml

# Configuration for production environment
namespace: permission-binder-system

commonLabels:
  app.kubernetes.io/name: permission-binder-operator
  app.kubernetes.io/part-of: permission-binder-operator
  environment: production

# Patches for production environment
patches:
  - target:
      kind: Deployment
      name: permission-binder-operator-controller-manager
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: lukaszbielinski/permission-binder-operator:v1.2.1
      - op: replace
        path: /spec/replicas
        value: 2
      - op: add
        path: /spec/template/spec/containers/0/resources
        value:
          requests:
            memory: "256Mi"
            cpu: "10m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
