apiVersion: v1
kind: ConfigMap
metadata:
  name: multi-tenant-permission-config
  namespace: default
  labels:
    app.kubernetes.io/name: permission-binder-operator
    app.kubernetes.io/instance: multi-tenant
data:
  # Whitelist format: LDAP DN entries with CN containing {PREFIX}-{NAMESPACE}-{ROLE}
  # Multi-tenant example with different prefixes and complex namespace structures
  whitelist.txt: |-
    # Tenant 1 permissions
    CN=MT-K8S-tenant1-project1-engineer,OU=Tenant1,OU=Kubernetes,DC=example,DC=com
    CN=MT-K8S-tenant1-project2-admin,OU=Tenant1,OU=Kubernetes,DC=example,DC=com
    
    # Tenant 2 permissions
    CN=MT-K8S-tenant2-app1-viewer,OU=Tenant2,OU=Kubernetes,DC=example,DC=com
    CN=MT-K8S-tenant2-app2-devops,OU=Tenant2,OU=Kubernetes,DC=example,DC=com
    
    # Environment-specific permissions (complex namespace names)
    CN=MT-K8S-tenant1-staging-staging-admin,OU=Staging,OU=Tenant1,DC=example,DC=com
    CN=MT-K8S-tenant2-production-production-viewer,OU=Production,OU=Tenant2,DC=example,DC=com
    
    # Specialized team permissions
    CN=MT-K8S-security-team-security,OU=Security,OU=Platform,DC=example,DC=com
    CN=MT-K8S-audit-team-auditor,OU=Audit,OU=Platform,DC=example,DC=com
    
    # System permissions (to be excluded via ExcludeList)
    # CN=MT-K8S-SYSTEM-admin,OU=System,DC=example,DC=com
    # CN=MT-K8S-MONITORING-viewer,OU=System,DC=example,DC=com
    # CN=MT-K8S-LOGGING-viewer,OU=System,DC=example,DC=com
