//go:build !ignore_autogenerated

/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutoMergeSpec) DeepCopyInto(out *AutoMergeSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutoMergeSpec.
func (in *AutoMergeSpec) DeepCopy() *AutoMergeSpec {
	if in == nil {
		return nil
	}
	out := new(AutoMergeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BatchProcessingSpec) DeepCopyInto(out *BatchProcessingSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BatchProcessingSpec.
func (in *BatchProcessingSpec) DeepCopy() *BatchProcessingSpec {
	if in == nil {
		return nil
	}
	out := new(BatchProcessingSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GitRepositorySpec) DeepCopyInto(out *GitRepositorySpec) {
	*out = *in
	if in.CredentialsSecretRef != nil {
		in, out := &in.CredentialsSecretRef, &out.CredentialsSecretRef
		*out = new(LdapSecretReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GitRepositorySpec.
func (in *GitRepositorySpec) DeepCopy() *GitRepositorySpec {
	if in == nil {
		return nil
	}
	out := new(GitRepositorySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LdapSecretReference) DeepCopyInto(out *LdapSecretReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LdapSecretReference.
func (in *LdapSecretReference) DeepCopy() *LdapSecretReference {
	if in == nil {
		return nil
	}
	out := new(LdapSecretReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NamespaceExcludeList) DeepCopyInto(out *NamespaceExcludeList) {
	*out = *in
	if in.Patterns != nil {
		in, out := &in.Patterns, &out.Patterns
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Explicit != nil {
		in, out := &in.Explicit, &out.Explicit
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NamespaceExcludeList.
func (in *NamespaceExcludeList) DeepCopy() *NamespaceExcludeList {
	if in == nil {
		return nil
	}
	out := new(NamespaceExcludeList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkPolicySpec) DeepCopyInto(out *NetworkPolicySpec) {
	*out = *in
	if in.GitRepository != nil {
		in, out := &in.GitRepository, &out.GitRepository
		*out = new(GitRepositorySpec)
		(*in).DeepCopyInto(*out)
	}
	if in.ExcludeNamespaces != nil {
		in, out := &in.ExcludeNamespaces, &out.ExcludeNamespaces
		*out = new(NamespaceExcludeList)
		(*in).DeepCopyInto(*out)
	}
	if in.ExcludeBackupForNamespaces != nil {
		in, out := &in.ExcludeBackupForNamespaces, &out.ExcludeBackupForNamespaces
		*out = new(NamespaceExcludeList)
		(*in).DeepCopyInto(*out)
	}
	if in.AutoMerge != nil {
		in, out := &in.AutoMerge, &out.AutoMerge
		*out = new(AutoMergeSpec)
		**out = **in
	}
	if in.BatchProcessing != nil {
		in, out := &in.BatchProcessing, &out.BatchProcessing
		*out = new(BatchProcessingSpec)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkPolicySpec.
func (in *NetworkPolicySpec) DeepCopy() *NetworkPolicySpec {
	if in == nil {
		return nil
	}
	out := new(NetworkPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkPolicyStatus) DeepCopyInto(out *NetworkPolicyStatus) {
	*out = *in
	if in.PRNumber != nil {
		in, out := &in.PRNumber, &out.PRNumber
		*out = new(int)
		**out = **in
	}
	if in.LastTemplateCheckTime != nil {
		in, out := &in.LastTemplateCheckTime, &out.LastTemplateCheckTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkPolicyStatus.
func (in *NetworkPolicyStatus) DeepCopy() *NetworkPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(NetworkPolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PermissionBinder) DeepCopyInto(out *PermissionBinder) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PermissionBinder.
func (in *PermissionBinder) DeepCopy() *PermissionBinder {
	if in == nil {
		return nil
	}
	out := new(PermissionBinder)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PermissionBinder) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PermissionBinderList) DeepCopyInto(out *PermissionBinderList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PermissionBinder, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PermissionBinderList.
func (in *PermissionBinderList) DeepCopy() *PermissionBinderList {
	if in == nil {
		return nil
	}
	out := new(PermissionBinderList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PermissionBinderList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PermissionBinderSpec) DeepCopyInto(out *PermissionBinderSpec) {
	*out = *in
	if in.RoleMapping != nil {
		in, out := &in.RoleMapping, &out.RoleMapping
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Prefixes != nil {
		in, out := &in.Prefixes, &out.Prefixes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ExcludeList != nil {
		in, out := &in.ExcludeList, &out.ExcludeList
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.LdapSecretRef != nil {
		in, out := &in.LdapSecretRef, &out.LdapSecretRef
		*out = new(LdapSecretReference)
		**out = **in
	}
	if in.LdapTlsVerify != nil {
		in, out := &in.LdapTlsVerify, &out.LdapTlsVerify
		*out = new(bool)
		**out = **in
	}
	if in.ServiceAccountMapping != nil {
		in, out := &in.ServiceAccountMapping, &out.ServiceAccountMapping
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.NetworkPolicy != nil {
		in, out := &in.NetworkPolicy, &out.NetworkPolicy
		*out = new(NetworkPolicySpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PermissionBinderSpec.
func (in *PermissionBinderSpec) DeepCopy() *PermissionBinderSpec {
	if in == nil {
		return nil
	}
	out := new(PermissionBinderSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PermissionBinderStatus) DeepCopyInto(out *PermissionBinderStatus) {
	*out = *in
	if in.ProcessedRoleBindings != nil {
		in, out := &in.ProcessedRoleBindings, &out.ProcessedRoleBindings
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ProcessedServiceAccounts != nil {
		in, out := &in.ProcessedServiceAccounts, &out.ProcessedServiceAccounts
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.NetworkPolicies != nil {
		in, out := &in.NetworkPolicies, &out.NetworkPolicies
		*out = make([]NetworkPolicyStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LastNetworkPolicyReconciliation != nil {
		in, out := &in.LastNetworkPolicyReconciliation, &out.LastNetworkPolicyReconciliation
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PermissionBinderStatus.
func (in *PermissionBinderStatus) DeepCopy() *PermissionBinderStatus {
	if in == nil {
		return nil
	}
	out := new(PermissionBinderStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceAccountRoleRef) DeepCopyInto(out *ServiceAccountRoleRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceAccountRoleRef.
func (in *ServiceAccountRoleRef) DeepCopy() *ServiceAccountRoleRef {
	if in == nil {
		return nil
	}
	out := new(ServiceAccountRoleRef)
	in.DeepCopyInto(out)
	return out
}
