apiVersion: v1
kind: Secret
metadata:
  name: ldap-credentials
  namespace: permissions-binder-operator
  labels:
    app.kubernetes.io/name: permission-binder-operator
    app.kubernetes.io/component: ldap-integration
type: Opaque
stringData:
  # LDAP/Active Directory server address (e.g., ldaps://ad.company.com:636 or ad.company.com:389)
  domain_server: "ldaps://ad.example.com:636"
  
  # Service account username for LDAP operations (e.g., CN=svc-k8s,OU=ServiceAccounts,DC=company,DC=com)
  domain_username: "CN=svc-k8s-operator,OU=ServiceAccounts,DC=example,DC=com"
  
  # Service account password
  domain_password: "ChangeMe123!"

