apiVersion: v1
kind: ConfigMap
metadata:
  name: permission-config
  namespace: permissions-binder-operator
  labels:
    app.kubernetes.io/name: permission-binder-operator
    app.kubernetes.io/instance: example
data:
  # Whitelist format: LDAP DN entries with CN containing {PREFIX}-{NAMESPACE}-{ROLE}
  # The operator extracts the CN value and parses it to create RoleBindings
  # Role is matched from PermissionBinder roleMapping keys
  # Namespace can contain hyphens (e.g., project-123, test-namespace-v2)
  # Multiple prefixes supported (longest matched first)
  whitelist.txt: |-
    # COMPANY-K8S prefix entries
    CN=COMPANY-K8S-project1-engineer,OU=Kubernetes,OU=Platform,DC=example,DC=com
    CN=COMPANY-K8S-project2-admin,OU=Kubernetes,OU=Platform,DC=example,DC=com
    CN=COMPANY-K8S-project3-viewer,OU=Kubernetes,OU=Platform,DC=example,DC=com
    
    # MT-K8S prefix entries (multi-tenant)
    CN=MT-K8S-tenant1-app1-engineer,OU=Tenant1,OU=Kubernetes,DC=example,DC=com
    CN=MT-K8S-tenant2-project-456-admin,OU=Tenant2,OU=Kubernetes,DC=example,DC=com
    
    # MT-K8S-DEV-K8S prefix entries (development tenant - longest prefix)
    CN=MT-K8S-DEV-K8S-staging-app-engineer,OU=Dev,OU=Kubernetes,DC=example,DC=com
    CN=MT-K8S-DEV-K8S-test-env-viewer,OU=Dev,OU=Kubernetes,DC=example,DC=com

