apiVersion: permission.permission-binder.io/v1
kind: PermissionBinder
metadata:
  name: permissionbinder-example
  namespace: permissions-binder-operator
  labels:
    app.kubernetes.io/name: permission-binder-operator
    app.kubernetes.io/instance: example
spec:
  # Mapping of roles to existing ClusterRoles
  roleMapping:
    engineer: edit
    admin: admin
    viewer: view
    read-only: read-only
  
  # Prefixes used to identify permission strings (supports multiple for multi-tenant scenarios)
  # Longest prefix is matched first (e.g., "MT-K8S-DEV" before "MT-K8S")
  prefixes:
    - "MT-K8S-DEV-K8S"
    - "COMPANY-K8S"
    - "MT-K8S"
  
  # Exclusion list (CN values to exclude from processing)
  excludeList:
    - "COMPANY-K8S-HPA-admin"
    - "MT-K8S-SYSTEM-admin"
    - "MT-K8S-MONITORING-viewer"
  
  # ConfigMap configuration
  configMapName: "permission-config"
  configMapNamespace: "permissions-binder-operator"
  
  # LDAP Group Creation (optional)
  # When enabled, the operator will automatically create LDAP groups for managed namespaces
  createLdapGroups: false
  
  # LDAP credentials reference (required if createLdapGroups is true)
  # The secret must contain: domain_server, domain_username, domain_password
  # ldapSecretRef:
  #   name: "ldap-credentials"
  #   namespace: "permissions-binder-operator"
  # 
  # TLS certificate verification (optional, default: true)
  # ldapTlsVerify: false  # Use only for self-signed certs (testing)

  # NetworkPolicy Management via GitOps (optional)
  networkPolicy:
    enabled: true
    
    # Git repository configuration
    gitRepository:
      provider: "github"  # github, bitbucket, or gitlab
      url: "https://github.com/lukasz-bielinski/tests-network-policies.git"
      baseBranch: "main"
      clusterName: "DEV-cluster"  # Used in path: networkpolicies/{clusterName}/...
      credentialsSecretRef:
        name: "github-gitops-credentials"
        namespace: "permissions-binder-operator"
    
    # Template directory in Git repo
    templateDir: "networkpolicies/templates"
    
    # Auto-merge configuration (only for Variant A - new file from template)
    autoMerge:
      enabled: true
      label: "auto-merge"
    
    # Global exclude list (blocks ALL NetworkPolicy operations)
    excludeNamespaces:
      explicit:
        - "kube-system"
        - "kube-public"
        - "kube-node-lease"
        - "openshift-*"
        - "ocp-*"
      patterns:
        - "^openshift-.*"
        - "^ocp-.*"
        - "^kube-.*"
    
    # Backup existing NetworkPolicies (optional, default: false)
    backupExisting: true
    
    # Exclude from backup (but still create from templates)
    excludeBackupForNamespaces:
      explicit: []
      patterns: []
    
    # Reconciliation interval (default: 1h)
    reconciliationInterval: "1h"
    
    # Status retention (default: 30 days)
    statusRetentionDays: 30
    
    # Stale PR threshold (default: 30d)
    stalePRThreshold: "30d"
    
    # Batch processing configuration
    batchProcessing:
      batchSize: 5
      sleepBetweenNamespaces: "3s"
      sleepBetweenBatches: "60s"

