apiVersion: permission.permission-binder.io/v1
kind: PermissionBinder
metadata:
  name: permissionbinder-example
  namespace: permissions-binder-operator
  labels:
    app.kubernetes.io/name: permission-binder-operator
    app.kubernetes.io/instance: example
spec:
  # Mapping of roles to existing ClusterRoles
  roleMapping:
    engineer: edit
    admin: admin
    viewer: view
    read-only: read-only
  
  # Prefixes used to identify permission strings (supports multiple for multi-tenant scenarios)
  # Longest prefix is matched first (e.g., "MT-K8S-DEV" before "MT-K8S")
  prefixes:
    - "MT-K8S-DEV-K8S"
    - "COMPANY-K8S"
    - "MT-K8S"
  
  # Exclusion list (CN values to exclude from processing)
  excludeList:
    - "COMPANY-K8S-HPA-admin"
    - "MT-K8S-SYSTEM-admin"
    - "MT-K8S-MONITORING-viewer"
  
  # ConfigMap configuration
  configMapName: "permission-config"
  configMapNamespace: "permissions-binder-operator"
  
  # LDAP Group Creation (optional)
  # When enabled, the operator will automatically create LDAP groups for managed namespaces
  createLdapGroups: false
  
  # LDAP credentials reference (required if createLdapGroups is true)
  # The secret must contain: domain_server, domain_username, domain_password
  # ldapSecretRef:
  #   name: "ldap-credentials"
  #   namespace: "permissions-binder-operator"

